import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2{
            font-size: 50px;
            margin: 15px 0px 25px 0px;
          }
          h3{
            font-size: 30px;
          }
        `}
      </style>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hunting coder
        </h1>

        <div className={styles.imagewrapper}>
          <Image className={styles.homeimg} alt="" src="/homeImg.webp" width={174} height={116} />
        </div>
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder.
        </p>

      <div className="blogs">
        <h2>Popular blogs:</h2>
        <div className="blogItem">
          <h3>How to learn JavaScript in 2022?</h3>
          <p>JavaScript is widely used for designing logic for the web.</p>
        </div>
        <div className="blogItem">
          <h3>How to learn JavaScript in 2022?</h3>
          <p>JavaScript is widely used for designing logic for the web.</p>
        </div>
        <div className="blogItem">
          <h3>How to learn JavaScript in 2022?</h3>
          <p>JavaScript is widely used for designing logic for the web.</p>
        </div>
      </div>
      </main>
    </div>
  )
}
