import Head from "next/head";
import styles from "../styles/Home.module.css";
import React from "react";
// import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.imagewrapper}>
          <img
            className={styles.homeimg}
            src="/homeImg.webp"
            width={116}
            height={116}
          ></img>
        </div>

        <h1 className={styles.title}>&lt;Hunting coder/&gt;</h1>

        <div className="blogs">
          <h2 className={styles.h2}>Popular blogs:</h2>
          <div>
            <h3 className={styles.h3}>How to learn JavaScript in 2022?</h3>
            <p className={styles.p}>
              JavaScript is widely used for designing logic for the web. Lorem
              ipsum dolor sit amet consectetur adipisicing elit. Rerum, sit?
            </p>
            <div className={styles.buttonwrapper}>
              <button className={styles.btn}>Read more</button>
            </div>
          </div>
          <div>
            <h3 className={styles.h3}>How to learn JavaScript in 2022?</h3>
            <p className={styles.p}>
              JavaScript is widely used for designing logic for the web. Lorem
              ipsum dolor sit amet consectetur adipisicing elit. Tenetur ullam.
            </p>
            <div className={styles.buttonwrapper}>
              <button className={styles.btn}>Read more</button>
            </div>
          </div>
          <div>
            <h3 className={styles.h3}>How to learn JavaScript in 2022?</h3>
            <p className={styles.p}>
              JavaScript is widely used for designing logic for the web. Lorem
              ipsum dolor sit amet consectetur adipisicing elit. Iure nesciunt.
            </p>
            <div className={styles.buttonwrapper}>
              <button className={styles.btn}>Read more</button>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
